### PR TITLE
fix: analysis step should be ignored after promote

### PR DESCRIPTION
**Pull request by pasha-codefresh**
Closes: #3015

### CODE REVIEW

**Comment by pasha-codefresh** [comment]
@zachaller could you please review? it is an issue that i showed to you

**Comment by pasha-codefresh** [comment]
Why codegen fails in this PR? i didnt change anything related to it

**Comment by zachaller** [comment]
> Why codegen fails in this PR? i didnt change anything related to it

Seems to have just been a bad run, I re-ran it and its good now

**Comment by pasha-codefresh** [comment]
Thank you @zachaller

**Review by zachaller — APPROVED** [review]

**Pull request merged**
