### PR TITLE
feat(controller): Add support for  ephemeral metadata on BlueGreen rollouts. Fixes #973

### LINKED ISSUE #973: Add Ephemeral Metadata for Blue Green strategy
# Summary

Functionality for setting ephemeral metadata for Canary rollouts was proposed in #455 and implemented in #770. I would like to extend this functionality to the BlueGreen strategy as well. This would be done by adding `previewMetadata` and `activeMetadata` to the BlueGreen spec and using similar reconciliation logic to apply them to the replicasets and pods.

# Use Cases

Same use cases as ephemeral metadata for canary rollouts (i.e. tagging metrics with consistent labels). My specific use case is to tag Prometheus metrics with a label if the pod is active and use that for selecting custom HPA metrics.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

### PR DESCRIPTION
**Pull request by cooperbenson-qz**
Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-rollouts/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [x] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [x] I've signed the CLA.
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My builds are green. Try syncing with master if they are not. 
* [x] My organization is added to [USERS.md](https://github.com/argoproj/argo-rollouts/blob/master/USERS.md).

### CODE REVIEW

**Comment by cooperbenson-qz** [comment]
Current status:
- Working on getting permission to sign the CLA from my org, should have that in an hour or so
- I'm a little worried that I've made the e2e tests flaky. I had to add sleeps to get them to work which seems suspect to me
- A documentation update is required, but I'm not sure how to go about it since the canary and blue-green terms are different and I don't want to add a bunch of redundant listing of terms

**Comment by jessesuen** [comment]
This looks great!

> Working on getting permission to sign the CLA from my org, should have that in an hour or so

DCO is sufficient. We've already moved off the CLA and will be disabling the bot.

> I'm a little worried that I've made the e2e tests flaky. I had to add sleeps to get them to work which seems suspect to me

There is a ongoing issue with e2e tests flaking because of `waiting for rollout spec update to be observed` so I will ignore those failures.

> A documentation update is required, but I'm not sure how to go about it since the canary and blue-green terms are different and I don't want to add a bunch of redundant listing of terms

We often refer to it as: desired (aka active/preview) vs. stable. For documentation, I'm thinking we can replace the use of canary with desired, along with an explanation that desired means canary or preview depending on the strategy.

**Comment by jessesuen** [comment]
The change looks straight forward and pretty much good to go. The e2e tests are not your fault so I think the only thing left to do is to update documentation.

Please add in the documentation markdown, a note saying that this feature is a v1.0 feature so that < 0.10 users won't be confused when it doesn't work. e.g.:

```
!!! important

    Blue-green ephemeral metadata available in v1.0
```

**Comment by cooperbenson-qz** [comment]
Thanks for the suggestion for the documentation. Just pushed the update to the relevant docs page and took the opportunity to fix the link to USERS.md

**Review by jessesuen — APPROVED** [review]
Great job and appreciate the e2e test for this!

**Comment by bobbyvacco** [comment]
> The change looks straight forward and pretty much good to go. The e2e tests are not your fault so I think the only thing left to do is to update documentation.
> 
> Please add in the documentation markdown, a note saying that this feature is a v1.0 feature so that < 0.10 users won't be confused when it doesn't work. e.g.:
> 
> ```
> !!! important
> 
>     Blue-green ephemeral metadata available in v1.0
> ```

is this meant to say available in v.0.10?

**Pull request merged**
