### PR TITLE
fix(dashboard): Update pod status logic to support native sidecars. Fixes #3366

### LINKED ISSUE #3366: Use of native SidecarContainers (init container with `restartPolicy: Always`) results in pod status getting stuck on `Init`
K8s 1.29 enables the `SidecarContainers` feature gate by default (more info on the native sidecars here https://kubernetes.io/docs/concepts/workloads/pods/sidecar-containers/)
These are defined as `initContainers` with the `restartPolicy` set to `Always`

This change in logic results in pods being perpetually (visually) stuck in the Init phase

This appears to have affected various software which interacts with k8s, eg the following issue on `k9s`
https://github.com/derailed/k9s/issues/2520

**Screenshots**
Screenshot 2024-02-13 at 11 07 29 AM

```
Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

### PR DESCRIPTION
**Pull request by martynd**
Closes https://github.com/argoproj/argo-rollouts/issues/3366
Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-rollouts/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [x] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/) with a list of types and scopes found [here](https://github.com/argoproj/argo-rollouts/blob/master/.github/workflows/pr-title-check.yml), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [x] I've signed my commits with [DCO](https://github.com/argoproj/argoproj)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My builds are green. Try syncing with master if they are not. 
* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo-rollouts/blob/master/USERS.md).

### CODE REVIEW

**Comment by Hronom** [comment]
Any news to make it not draft?

**Comment by martynd** [comment]
> Any news to make it not draft?

I need a change to add tests as its failing the coverage checks. Theres no existing tests for any of this however to just extend which complicates it a little

**Comment by Hronom** [comment]
Nice, can't wait for support for native sidecars. Right now Argo Rollouts some sort of blocker for it

**Comment by rsavage-nozominetworks** [comment]
Hi folks, any way to make this a priority?   Seeing the same issue here.

**Comment by martynd** [comment]
Ive still not got around to doing the tests but I've marked it as ready anyway in case the maintainers are willing to waive the requirement given the absence of testing for for all the functionality there in any form

**Comment by rsavage-nozominetworks** [comment]
> Ive still not got around to doing the tests but I've marked it as ready anyway in case the maintainers are willing to waive the requirement given the absence of testing for for all the functionality there in any form

How can we get the maintainers involved?  Seems like they are ignoring this issue.  I posted a message in the argo-rollouts slack channel yesterday, and zero response.

**Comment by tbronchain** [comment]
Facing the issue also.

I manage to still use Argo (rollouts/cd) but the rollout status is not properly reported to ArgoCD, which *seems* to trigger a "bug" with some replicaset showing as ProgressDeadlineExceeded (https://github.com/argoproj/argo-rollouts/issues/3457).

The Issue seem to be "cosmetics" only (rollouts are properly promoted) but I'm wondering if some extra logic is being used during deployments, it may break.

Big thanks to whoever will look into this :)

**Review by zachaller — APPROVED** [review]

**Comment by zachaller** [comment]
Can you fix the lint issue by running `make lint`

**Comment by Hronom** [comment]
Hello, do you have sense when it will be released approximately?

Asking because it becomes a major blocker to enable sidecars nowadays if you have in your stack Argo Rollouts.

**Review by zachaller — APPROVED** [review]

**Comment by Hronom** [comment]
Hello, @zachaller do you have sense when it will be released?

**Pull request merged**
