### PR TITLE
feat: added Argo version info in /metrics endpoint

### PR DESCRIPTION
**Pull request by smaloo-salesforce**
Signed-off-by: Siddharth Maloo <smaloo@salesforce.com>

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-rollouts/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [x] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [x] I've signed my commits with [DCO](https://github.com/argoproj/argoproj)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My builds are green. Try syncing with master if they are not. 
* [x] My organization is added to [USERS.md](https://github.com/argoproj/argo-rollouts/blob/master/USERS.md).

### CODE REVIEW

**Comment by smaloo-salesforce** [comment]
> Could we have a unit test for this new field?

Hi @jessesuen - I had added the check in one of the existing test function as its a constant metric.
Moved it to new test function. Let me know if that looks fine. 
Function name - `TestVersionInfo`

**Review by alexmt — APPROVED** [review]
LGTM

**Comment by alexmt** [comment]
@smaloo-salesforce  can you resolve merge conflicts please?

**Comment by smaloo-salesforce** [comment]
Hi @alexmt @jessesuen 
My commit history got corrupted for this PR.
I have raised another PR for the same changes - #1662 
Could you please approve and merge that one instead. I will close this. Sorry for inconvenience 

cc; @huikang

**Pull request closed without merging**
