### PR TITLE
fix: Revert "chore: update k8s pkg to resolve vulnerabilities "

### PR DESCRIPTION
**Pull request by harikrongali**
Reverts argoproj/argo-rollouts#1545
Causes unit tests to fail locally:
```
        	Error Trace:	list_test.go:182
        	Error:      	Received unexpected error:
        	            	permission denied
        	Test:       	TestListNamespaceAndTimestamp
```

### CODE REVIEW

**Review by khhirani — APPROVED** [review]

**Comment by huikang** [comment]
Hi, @harikrongali , is there something to be configured in your local dev environment? The Ci looks fine with the updated k8s client pkg.

**Comment by huikang** [comment]
Hi, @harikrongali , instead of reverting the change (which brings back the vulnerability issue), is it possible to update the `TestListNamespaceAndTimestamp` unit test to avoid the permission requirement?

**Comment by harikrongali** [comment]
@huikang actually there are 185+ tests are failing with the same error. I verified with multiple contributors and all have the same issue.
Can you confirm if you are able to do make test locally?

**Comment by harikrongali** [comment]
added https://github.com/argoproj/argo-rollouts/issues/1653
we can hold off in merging the PR

**Comment by jessesuen** [comment]
Can we close this now that https://github.com/argoproj/argo-rollouts/pull/1654 is merged?

**Pull request closed without merging**
