### PR TITLE
fix(controller): stuck in scale event after canary service switch delay. Fixes #3412

### LINKED ISSUE #3412: Rollout stuck when a scale event happens durring a service switch delay
Checklist:

* [x] I've included steps to reproduce the bug.
* [x] I've included the version of argo rollouts.

**Describe the bug**

Rollout controller in a infinity loop trying to reconcile a still referenced replicaset.

**To Reproduce**

I made this e2e test, just a easy way to test the problem, need to use a E2E_POD_DELAY=3 for the service switch delay
```
func (s *CanarySuite) TestRolloutScalingWhenChanged() {
	s.Given().
		RolloutObjects(`@functional/alb-canary-rollout.yaml`).
		When().
		ApplyManifests().
		WaitForRolloutStatus("Healthy").
		UpdateSpec().
		WaitForRolloutStatus("Paused").
		UpdateSpec().
                Sleep(2*time.Second). // Should be less than E2E_POD_DELAY
		ScaleRollout(3).
                Sleep(30*time.Second). // Just to stop the execution before delete the rollout
		Then().
		ExpectRevisionPodCount("1", 3).
		ExpectRevisionPodCount("2", 0).
		ExpectRevisionPodCount("3", 1)
}
```

**Expected behavior**

The controller should be able to reconcile the rollout/services.

**Version**

1.6.6

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

### PR DESCRIPTION
**Pull request by BrunoTarijon**
Start a service reconcile if a rs is "still referenced" to fix [this issue](https://github.com/argoproj/argo-rollouts/issues/3412).

WIP - e2e test

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-rollouts/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [x] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/) with a list of types and scopes found [here](https://github.com/argoproj/argo-rollouts/blob/master/.github/workflows/pr-title-check.yml), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [x] I've signed my commits with [DCO](https://github.com/argoproj/argoproj)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My builds are green. Try syncing with master if they are not. 
* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo-rollouts/blob/master/USERS.md).

### CODE REVIEW

**Comment by jessesuen** [comment]
> Rollout controller in a infinity loop trying to reconcile a still referenced replicaset.
> All reconciles in this rollout execute the isEscaleEvent, **_and will never make the service switch._**

The approach that this PR takes, is that it introduces reconciliation of the rollouts services, even if the rollout is in an `isScalingEvent`. However, the original intent/design was to not reconcile **_anything but replicaset counts_** during a scaling event, and leave normal reconciliation to handle things like service reconciliation. So this PR will break that rule.

> **_and will never make the service switch._**

I would like to confirm/deny if this statement is accurate. My belief is that it **_eventually will_**, but only upon the next reconciliation of the Rollout. In your testing, if you were to either:
1. wait 15 minutes (the default rollout resync period)
2. restart the controller
3. tickle the rollout (e.g. add an annotation)

I believe the rollout would get "unstuck". If what I say is true, then I think the fix should be done in a different way. That is, the scaling Event could requeue the rollout so that it performs normal reconciliation to unstuck itself for the service.

NOTE: I haven't tested my claims, so I could be completely off base. But I'd like to confirm if what I'm saying is true.

**Comment by BrunoTarijon** [comment]
I did the test here to confirm.

Waited for 20 minutes. After that, restart the make start-e2e (I think it is the same as restarting the controller). It still stuck.
image

<details>
<summary>Logs</summary>


```
INFO[0060] Started syncing rollout                       generation=5 namespace=default resourceVersion=79977 rollout=alb-canary-with-delay
INFO[0060] Syncing replicas only due to scaling event    namespace=default rollout=alb-canary-with-delay
INFO[0060] Reconciling 1 old ReplicaSets (total pods: 1)  namespace=default rollout=alb-canary-with-delay
INFO[0060] Found 1 available pods in old RS default/alb-canary-with-delay-59ffd4945b  namespace=default rollout=alb-canary-with-delay
INFO[0060] Found 5 available pods, scaling down old RSes (minAvailable: 3, maxScaleDown: 2)  namespace=default rollout=alb-canary-with-delay
INFO[0060] Proceed with scaledown: true                  namespace=default rollout=alb-canary-with-delay
INFO[0060] Skip scale down of older RS 'alb-canary-with-delay-59ffd4945b': still referenced  namespace=default rollout=alb-canary-with-delay
INFO[0060] No status changes. Skipping patch             generation=5 namespace=default resourceVersion=79977 rollout=alb-canary-with-delay
INFO[0060] Queueing up Rollout for a progress check now  namespace=default rollout=alb-canary-with-delay
INFO[0060] Reconciliation completed                      generation=5 namespace=default resourceVersion=79977 rollout=alb-canary-with-delay time_ms=0.43729100000000004
INFO[0060] Started syncing rollout                       generation=5 namespace=default resourceVersion=79977 rollout=alb-canary-with-delay
INFO[0060] Syncing replicas only due to scaling event    namespace=default rollout=alb-canary-with-delay
INFO[0060] Reconciling 1 old ReplicaSets (total pods: 1)  namespace=default rollout=alb-canary-with-delay
INFO[0060] Found 1 available pods in old RS default/alb-canary-with-delay-59ffd4945b  namespace=default rollout=alb-canary-with-delay
INFO[0060] Found 5 available pods, scaling down old RSes (minAvailable: 3, maxScaleDown: 2)  namespace=default rollout=alb-canary-with-delay
INFO[0060] Proceed with scaledown: true                  namespace=default rollout=alb-canary-with-delay
INFO[0060] Skip scale down of older RS 'alb-canary-with-delay-59ffd4945b': still referenced  namespace=default rollout=alb-canary-with-delay
INFO[0060] No status changes. Skipping patch             generation=5 namespace=default resourceVersion=79977 rollout=alb-canary-with-delay
INFO[0060] Queueing up Rollout for a progress check now  namespace=default rollout=alb-canary-with-delay
INFO[0060] Reconciliation completed                      generation=5 namespace=default resourceVersion=79977 rollout=alb-canary-with-delay time_ms=0.468333
INFO[0060] Started syncing rollout                       generation=5 namespace=default resourceVersion=79977 rollout=alb-canary-with-delay
INFO[0060] Syncing replicas only due to scaling event    namespace=default rollout=alb-canary-with-delay
INFO[0060] Reconciling 1 old ReplicaSets (total pods: 1)  namespace=default rollout=alb-canary-with-delay
INFO[0060] Found 1 available pods in old RS default/alb-canary-with-delay-59ffd4945b  namespace=default rollout=alb-canary-with-delay
INFO[0060] Found 5 available pods, scaling down old RSes (minAvailable: 3, maxScaleDown: 2)  namespace=default rollout=alb-canary-with-delay
INFO[0060] Proceed with scaledown: true                  namespace=default rollout=alb-canary-with-delay
INFO[0060] Skip scale down of older RS 'alb-canary-with-delay-59ffd4945b': still referenced  namespace=default rollout=alb-canary-with-delay
INFO[0060] No status changes. Skipping patch             generation=5 namespace=default resourceVersion=79977 rollout=alb-canary-with-delay
INFO[0060] Queueing up Rollout for a progress check now  namespace=default rollout=alb-canary-with-delay
INFO[0060] Reconciliation completed                      generation=5 namespace=default resourceVersion=79977 rollout=alb-canary-with-delay time_ms=2.182709
INFO[0060] Started syncing rollout                       generation=5 namespace=default resourceVersion=79977 rollout=alb-canary-with-delay
INFO[0060] Syncing replicas only due to scaling event    namespace=default rollout=alb-canary-with-delay
INFO[0060] Reconciling 1 old ReplicaSets (total pods: 1)  namespace=default rollout=alb-canary-with-delay
INFO[0060] Found 1 available pods in old RS default/alb-canary-with-delay-59ffd4945b  namespace=default rollout=alb-canary-with-delay
INFO[0060] Found 5 available pods, scaling down old RSes (minAvailable: 3, maxScaleDown: 2)  namespace=default rollout=alb-canary-with-delay
INFO[0060] Proceed with scaledown: true                  namespace=default rollout=alb-canary-with-delay
INFO[0060] Skip scale down of older RS 'alb-canary-with-delay-59ffd4945b': still referenced  namespace=default rollout=alb-canary-with-delay
INFO[0060] No status changes. Skipping patch             generation=5 namespace=default resourceVersion=79977 rollout=alb-canary-with-delay
INFO[0060] Queueing up Rollout for a progress check now  namespace=default rollout=alb-canary-with-delay
INFO[0060] Reconciliation completed                      generation=5 namespace=default resourceVersion=79977 rollout=alb-canary-with-delay time_ms=0.5967089999999999
```

</details>

**Comment by BrunoTarijon** [comment]
Maybe I can requeue the rollout and add some kind of skip scale.

**Comment by cyrilico** [comment]
We have faced this in our organization, it would be an important issue to solve 🙏

**Pull request closed without merging**
