### PR TITLE
docs: fix broken links

### LINKED ISSUE #3983: broken link in https://argoproj.github.io/argo-rollouts/features/canary/ ( Anti Affinity document )
https://argoproj.github.io/argo-rollouts/features/canary/

image

### PR DESCRIPTION
**Pull request by blkperl**
fixes #3983

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-rollouts/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [x] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/) with a list of types and scopes found [here](https://github.com/argoproj/argo-rollouts/blob/master/.github/workflows/pr-title-check.yml), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [x] I've signed my commits with [DCO](https://github.com/argoproj/argoproj/blob/main/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My builds are green. Try syncing with master if they are not. 
* [x] My organization is added to [USERS.md](https://github.com/argoproj/argo-rollouts/blob/master/USERS.md).

I fixed most of the warnings shown when running

```
make serve-docs
```

### CODE REVIEW

**Review by zachaller — APPROVED** [review]

**Review by zachaller — DISMISSED** [review]

**Comment by zachaller** [comment]
I think think these links are actually broken on the hosted site: https://argo-rollouts.readthedocs.io/en/latest/FAQ/

**Comment by blkperl** [comment]
> I think think these links are actually broken on the hosted site: https://argo-rollouts.readthedocs.io/en/latest/FAQ/
> 
> I only checked the best practices link

What do you mean they are broken on the hosted site?

**Comment by zachaller** [comment]
You edited the FAQ's best practices link but you will notice it's not broken here https://argo-rollouts.readthedocs.io/en/latest/FAQ/

**Comment by blkperl** [comment]
> You edited the FAQ's best practices link but you will notice it's not broken here https://argo-rollouts.readthedocs.io/en/latest/FAQ/

Oh interesting, I guess `make serve-docs` throws a warning and Goland shows an error but then when they are served it becomes a 404.

**Comment by blkperl** [comment]
Well this needs more work, so i will close it for now.

**Pull request closed without merging**
