### PR TITLE
docs: Add best practice for reducing memory usage

### PR DESCRIPTION
**Pull request by blkperl**
Signed-off-by: William Van Hevelingen <william.vanhevelingen@acquia.com>

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-rollouts/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [x] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/) with a list of types and scopes found [here](https://github.com/argoproj/argo-rollouts/blob/master/.github/workflows/pr-title-check.yml), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [x] I've signed my commits with [DCO](https://github.com/argoproj/argoproj)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My builds are green. Try syncing with master if they are not. 
* [x] My organization is added to [USERS.md](https://github.com/argoproj/argo-rollouts/blob/master/USERS.md).

### CODE REVIEW

**Review by zachaller — APPROVED** [review]

**Comment by blkperl** [comment]
@zachaller Thanks for the review! Let me know if you have questions or suggestions on changing the wording.  

We could also mention that operators may wish to do the same for Deployments as the argo-controller watches all ReplicaSets on the clusters. One way to avoid this is to use NewCache which I don't think the controller uses. I can open a new issue for this if you think that makes sense. The tigera operator uses NewCache with a filter for NetworkPolicies if you are looking for an example.

- https://github.com/tigera/operator/blob/master/main.go#L231-L235
- https://github.com/argoproj-labs/argocd-operator/blob/master/main.go#L123
- https://master.sdk.operatorframework.io/docs/best-practices/designing-lean-operators/

**Comment by zachaller** [comment]
Yea I would love a new issue for looking into using that cache to get an informer that is more limited in scope that say all replicasets to reduce memory usage. Rollouts was created before a lot of the kubebuilder stuff so there is quite a few things done a little lower level but I took a quick peak at that cache package and it looks like I can get an informer still off of it so I would like to spend time looking into that and would use the issue to help track that.

**Comment by zachaller** [comment]
I think rollouts might need to do something like this instead of the cache

```
kubeInformerFactory := kubeinformers.NewSharedInformerFactoryWithOptions(
				kubeClient,
				resyncDuration,
				kubeinformers.WithNamespace(namespace), kubeinformers.WithTweakListOptions(func(options *metav1.ListOptions) {
					options.LabelSelector = "app=nats-box"
				}))
```

The key being WithTweakListOptions

**Comment by blkperl** [comment]
Thanks, I filed #2552

**Pull request merged**
