### PR TITLE
bugfix: kubectl argo create:161, command panic: runtime error: invali…

### PR DESCRIPTION
**Pull request by zhaoyun006**
…d memory address or nil pointer dereference

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-rollouts/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [ ] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [x] I've signed the CLA.
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My builds are green. Try syncing with master if they are not. 
* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo-rollouts/blob/master/USERS.md).

### CODE REVIEW

**Comment by zhaoyun006** [comment]
Is anyone here

**Comment by jessesuen** [comment]
Hi @zhaoyun006 the change looks good to me, could you sign your commit e.g. `git commit --amend -s` so that it can pass the DCO check?

**Comment by zhaoyun006** [comment]
> Hi @zhaoyun006 the change looks good to me, could you sign your commit e.g. `git commit --amend -s` so that it can pass the DCO check?

ok

**Comment by zhaoyun006** [comment]
> Hi @zhaoyun006 the change looks good to me, could you sign your commit e.g. `git commit --amend -s` so that it can pass the DCO check?

It's done!

**Comment by zhaoyun006** [comment]
> Hi @zhaoyun006 the change looks good to me, could you sign your commit e.g. `git commit --amend -s` so that it can pass the DCO check?

It's done!

**Pull request merged**
