### PR TITLE
docs: generate kubectl plugin docs

### LINKED ISSUE #327: Auto-generate kubectl argo rollouts docs for website
We should investigate and see if we can auto-generate documentation for the kubectl plugin

### PR DESCRIPTION
**Pull request by cronik**
add new `make plugin-docs` command that generates kubectl plugin docs to
`docs/generated`. a new navigation item is added under the 'Kubectl Plugin'
section that points to generated docs.

closes #327

### CODE REVIEW

**Comment by dthomson25** [comment]
Unless you have any other changes, I'll merge it in!

**Comment by cronik** [comment]
@dthomson25 I wasn't sure exactly how the docs were built and published. That process now requires an additional step of "make plugin-docs", if that's something I can update let me know.

**Comment by dthomson25** [comment]
The docs are published by running `mkdocs gh-deploy`, but it makes a git commit so only committors can run it.

**Comment by cronik** [comment]
I added a new make target to `release-docs` which will generate the docs before running the `gh-deploy`.

**Comment by dthomson25** [comment]
@cronik CI failed with 
```
+ tee /tmp/test-results/go-test.out
Makefile:127: *** missing separator.  Stop.
```. Are you able to run `make test` locally?

**Comment by dthomson25** [comment]
Great CI is now passing! I'll merge it in unless you have any other changes you want!

**Comment by cronik** [comment]
no more changes, merge away.

**Pull request merged**
