### PR TITLE
fix: unsolicited rollout after upgrade from v0.10->v1.0 when pod was using service account

### PR DESCRIPTION
**Pull request by jessesuen**
Partially fixes https://github.com/argoproj/argo-rollouts/issues/1356

Signed-off-by: Jesse Suen <jesse_suen@intuit.com>

### CODE REVIEW

**Comment by huikang** [comment]
Hi, @jessesuen , I am just wondering what if the existing pod has both serviceAccountName and serviceAccount in the template. Will this PR handle the case properly? Thanks.

**Review by khhirani — APPROVED** [review]
LGTM

**Comment by jessesuen** [comment]
> Hi, @jessesuen , I am just wondering what if the existing pod has both serviceAccountName and serviceAccount in the template. Will this PR handle the case properly? Thanks.

First, serviceAccountName and serviceAccount should always be the same value. I just verified that if you try to create a Deployment with different values, serviceAccount will get overridden with value from serviceAccountName.

Given that, `serviceAccountName` is the only thing we should care about. Users should be able to modify this field (add/remove/update), and the rollout should properly detect this as a change and perform an update.

However, the `serviceAccount` field in the pod is safe to ignore completely. It is a deprecated kubernetes field which has special treatment in k8s codebase. AFIK, there is not any other field in the pod spec which has this special treatment. The serviceAccount field is auto-populated in a special way (not by pod spec defaulting) because it derives its value from serviceAccount. We incorrectly detect the absence of this in the desired spec as a change in the pod template.

NOTE for this to happen, ComputeHash would have had to have changed meaning from underneath us. Something which I will address in a v1.1 specific PR.

**Comment by huikang** [comment]
> > Hi, @jessesuen , I am just wondering what if the existing pod has both serviceAccountName and serviceAccount in the template. Will this PR handle the case properly? Thanks.
> 
> First, serviceAccountName and serviceAccount should always be the same value. I just verified that if you try to create a Deployment with different values, serviceAccount will get overridden with value from serviceAccountName.
> 
> Given that, `serviceAccountName` is the only thing we should care about. Users should be able to modify this field (add/remove/update), and the rollout should properly detect this as a change and perform an update.
> 
> However, the `serviceAccount` field in the pod is safe to ignore completely. It is a deprecated kubernetes field which has special treatment in k8s codebase. AFIK, there is not any other field in the pod spec which has this special treatment. The serviceAccount field is auto-populated in a special way (not by pod spec defaulting) because it derives its value from serviceAccountName. We incorrectly detect the absence of serviceAccount in the desired spec as a change in the pod template, which causes the unsolicited update.
> 
> NOTE for this to happen, ComputeHash would have had to have changed meaning from underneath us. Something which I will address in a v1.1 specific PR.

Thanks for the detailed explanation

**Pull request merged**
