### PR TITLE
fix: Upgrade go-retryablehttp to v0.7.7

### PR DESCRIPTION
**Pull request by Rizwana777**
fixes https://github.com/argoproj/argo-rollouts/issues/3700

### CODE REVIEW

**Review by jgwest — APPROVED** [review]
LGTM: 
- Confirmed that all the dependency updates in `go.mod` are directly related to the upgrade of `go-retryablehttp` to the requisite version to fix the CVE
- Unit tests and E2E tests are passing, no issues in test logs

**Comment by Rizwana777** [comment]
Hi @zachaller can you please review and merge this PR?

**Comment by blkperl** [comment]
hey @Rizwana777 can you fix the merge conflict please?

**Comment by Rizwana777** [comment]
> hey @Rizwana777 can you fix the merge conflict please?

Hi @blkperl Fixed conflicts, PTAL

**Review by blkperl — APPROVED** [review]

**Review by zachaller — APPROVED** [review]

**Pull request merged**
