### PR TITLE
docs: make it clear that kustomize is required for unit tests

### PR DESCRIPTION
**Pull request by kostis-codefresh**
Signed-off-by: Kostis Kapelonis <kostis@codefresh.io>

Checklist:

* [X] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-rollouts/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [X] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [X] I've signed my commits with [DCO](https://github.com/argoproj/argoproj)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My builds are green. Try syncing with master if they are not. 
* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo-rollouts/blob/master/USERS.md).

### CODE REVIEW

**Review by huikang — COMMENTED** [review]
How about updating the Pre-requisites (https://github.com/argoproj/argo-rollouts/blob/master/docs/CONTRIBUTING.md#pre-requisites) by emphasizing kustomize; currently the Pre-requisites seems overlook `kustomize`.

**Comment by kostis-codefresh** [comment]
@huikang I updated the prereq section.  I am indifferent towards this PR. Feel free to reject/close it completely if you think it is not needed.

It is just that in my mind kustomize is a tool used for deployments and I never expected it to be used in unit tests. I would expect e2e tests to require kustomize, but not plain unit tests.

I guess if somebody wants to contribute to Argo Rollouts, they will install all tools in the prereqs section anyway, so this PR might be superfluous.

**Review by huikang — APPROVED** [review]
LGTM

**Review by alexmt — APPROVED** [review]
Thank you!

**Pull request merged**
