### PR TITLE
feat: allow analysis run to use separate kubeconfig for jobs

### LINKED ISSUE #3337: Option to specify a different KUBECONFIG where Analysis vs. Jobs would run
# Summary

Currently, when using the Job metric, the Job object will be created in the same cluster where the AnalysisRun resides. This proposal is to introduce a configuration option (environment variable) where a JOB_KUBECONFIG could be pointed to a **_different_** cluster where Jobs would be created (different from the AnalysisRuns).

# Use Cases

Having this option would enable some multi-cluster use cases, namely the ability for AnalysisTemplates, AnalysisRuns to be defined at a central location, without having to deploy/distribute the CRDs or AnalysisTemplates/Runs to workload clusters.

This should of course be an optional setting -- if the option is unspecified, the controller would maintain the current behavior. 

## Other notes

In addition to having a remote setting, the jobs should also have the option to be created using in-cluster credentials (instead of static credentials).

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

### PR DESCRIPTION
**Pull request by gdsoumya**
Fixes #3337 

This PR :
1. Enables setting `ARGO_ROLLOUTS_ANALYSIS_JOB_KUBECONFIG` to specify custom k8s config for running analysis jobs.
2. Also provides `ARGO_ROLLOUTS_ANALYSIS_JOB_NAMESPACE` to specify a different namespace from the analysis run to execute the job.

NOTE:

Setting custom `ARGO_ROLLOUTS_ANALYSIS_JOB_NAMESPACE` and `ARGO_ROLLOUTS_ANALYSIS_JOB_KUBECONFIG` will prevent automatic GC of jobs when analysis runs are deleted.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-rollouts/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [x] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/) with a list of types and scopes found [here](https://github.com/argoproj/argo-rollouts/blob/master/.github/workflows/pr-title-check.yml), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [x] I've signed my commits with [DCO](https://github.com/argoproj/argoproj)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My builds are green. Try syncing with master if they are not. 
* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo-rollouts/blob/master/USERS.md).

### CODE REVIEW

**Review by jessesuen — APPROVED** [review]
I did a careful review of this one and could not find anything. This LGTM!

**Comment by jessesuen** [comment]
@zachaller did you want a chance to review this before merging? FWIW, we have also done manual, end-to-end testing of the feature.

**Comment by zachaller** [comment]
I will take deeper look tomorrow, however one of my first thoughts is consistency with ENV var naming. Due to past [conventions](https://github.com/argoproj/argo-rollouts/pull/1956#discussion_r855856441) both plugins and various metric providers use `ARGO_ROLLOUTS_`  prefixes for env vars. I lean towards keeping consistent with that even though this somewhat piggy backs of of kubeclients KUBECONFIG env var. I tend to always prefer consistency though. Thoughts?

**Comment by gdsoumya** [comment]
> I will take deeper look tomorrow, however one of my first thoughts is consistency with ENV var naming. Due to past [conventions](https://github.com/argoproj/argo-rollouts/pull/1956#discussion_r855856441) both plugins and various metric providers use `ARGO_ROLLOUTS_` prefixes for env vars. I lean towards keeping consistent with that even though this somewhat piggy backs off of kubeclients KUBECONFIG env var. I tend to always prefer consistency though. Thoughts?

Would you prefer `ARGO_ROLLOUT_ANALYSIS_JOB_KUBECONFIG` and `ARGO_ROLLOUTS_ANALYSIS_JOB_NAMESPACE` ? I dropped the prefix as the env was getting a bit long and also because we recently added the only analysis mode which makes it a standalone feature so thought just having `ANALYSIS_` prefix might work. Though I don't have a strong opinion on this and if you and @jessesuen feel a bigger env name isn't a issue I'll add it.

**Comment by jessesuen** [comment]
Thanks @zachaller, that's a great call out. I agree the ARGO_ROLLOUTS_ prefix is an important convention to keep. So despite the long name, let's use that.

**Comment by gdsoumya** [comment]
Updated env names

**Review by zachaller — APPROVED** [review]
LGTM

**Pull request merged**
