### PR TITLE
feat(analysis): Added additional metadata to the status of AnalysisRun to be used by Prometheus Provider

### PR DESCRIPTION
**Pull request by agrawroh**
# Background

Currently, **AnalsysRun** doesn't display the prometheus query with resolved arguments which makes it a little bit harder to do any troubleshooting on the **AnalysisTemplate**.

**See:** https://github.com/argoproj/argo-rollouts/issues/1591

# Changes

In this PR, we are adding an additional `Metadata` in the metric results so that providers can use it to store any additional metadata they'd like to display in the AnalysisRuns. In case of prometheus, we store the final resolved query by substituting the template arguments.  

**Note:** This is only addressing the Prometheus Provider as of now.

# Checklist

* [X] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-rollouts/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [X] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [X] I've signed my commits with [DCO](https://github.com/argoproj/argoproj)
* [X] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [X] My builds are green. Try syncing with master if they are not. 
* [X] My organization is added to [USERS.md](https://github.com/argoproj/argo-rollouts/blob/master/USERS.md).

---
**Signed-off-by: Rohit Agrawal <rohit.agrawal@databricks.com>**

### CODE REVIEW

**Review by huikang — APPROVED** [review]

**Comment by huikang** [comment]
Hi, @agrawroh , it would be nice if we can add some explanation about the change to the doc: https://github.com/argoproj/argo-rollouts/blob/master/docs/analysis/prometheus.md

Thanks.

**Comment by agrawroh** [comment]
@jessesuen Could you help merge this PR?

**Review by huikang — APPROVED** [review]

**Review by huikang — APPROVED** [review]

**Comment by harikrongali** [comment]
@agrawroh seems PR addresses only Prometheus provider. can you add a description to the ticket that current PR address Prometheus provider only?

**Comment by agrawroh** [comment]
> @agrawroh seems PR addresses only Prometheus provider. can you add a description to the ticket that current PR address Prometheus provider only?

@huikang Done! Thanks

**Pull request merged**
