### PR TITLE
feat(controller): Add custom metadata support for AnalysisRun. Fixes #2740

### LINKED ISSUE #2740: Allow defining custom annotations and labels for AnalysisRun
# Summary

I didn't find the way to define the custom metadata (`labels` or `annotations`) on the `AnalysisRun` resource.
Looking at [the source code](https://github.com/argoproj/argo-rollouts/blob/3c9c29178b147e431b1bd4ff54ab5b00671893f6/rollout/analysis.go#L459), I found the static creation for those properties.

This feature is going to address this limitation and allow the user to define the custom `labels` and `annotations` of `AnalysisRun` base on the `Rollout` template.

# Use Cases

We recently introduced the ArgoCD [external URL](https://argo-cd.readthedocs.io/en/stable/user-guide/external-url/) and our engineers liked that feature. For our ArgoCD resources we are generating the service specific links like (Kibana or Datadog). 
One of our use cases is to provide the Kibana link for `AnalysisRun` with the version context. This will allow us to jump into the filtered logs for failing `AnalysisRun`. 

This is our use case but, I can imagine other cases where we could use this feature to group/filter `AnalysisRun` resources.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

### PR DESCRIPTION
**Pull request by lukaszgyg**
Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-rollouts/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [x] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/) with a list of types and scopes found [here](https://github.com/argoproj/argo-rollouts/blob/master/.github/workflows/pr-title-check.yml), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [x] I've signed my commits with [DCO](https://github.com/argoproj/argoproj)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My builds are green. Try syncing with master if they are not. 
* [x] My organization is added to [USERS.md](https://github.com/argoproj/argo-rollouts/blob/master/USERS.md).

### CODE REVIEW

**Comment by lukaszgyg** [comment]
This PR is the implementation for [#2740](https://github.com/argoproj/argo-rollouts/issues/2740)

**Comment by zachaller** [comment]
Will give this a code review in just a bit, but in the meantime can you also add to the spec docs https://argoproj.github.io/argo-rollouts/features/specification/

**Comment by lukaszgyg** [comment]
@zachaller I added the docs spec. Can you review the PR?

**Review by zachaller — APPROVED** [review]

**Comment by alexef** [comment]
@zachaller I assume this will be part of 1.6, not sooner, or?

**Comment by zachaller** [comment]
@alexef Yea it would be a new feature not a bug fix so would go in 1.6

**Pull request merged**
