### PR TITLE
fix: Add namespace if needed for ambassador services (#1417)

### PR DESCRIPTION
**Pull request by cldmnky**
Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-rollouts/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [x] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [x] I've signed my commits with [DCO](https://github.com/argoproj/argoproj)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My builds are green. Try syncing with master if they are not. 
* [x] My organization is added to [USERS.md](https://github.com/argoproj/argo-rollouts/blob/master/USERS.md).

### CODE REVIEW

**Comment by jessesuen** [comment]
@leoluz - do you mind take a look at this change?

**Comment by harikrongali** [comment]
@leoluz please review the PR

**Comment by leoluz** [comment]
@cldmnky Please see https://github.com/argoproj/argo-rollouts/issues/1417#issuecomment-918543966

**Comment by leoluz** [comment]
As discussed in the ticket this PR fixes an issue that in only present in Ambassador versions prior to 1.0.0 which aren't supported anymore as they are almost 2 years old.

**Comment by jessesuen** [comment]
Closing as wontfix

**Pull request closed without merging**
