### PR TITLE
fix(controller): prevent negative vsvc weights on a replica scaledown following a canary abort for istio trafficrouting

### PR DESCRIPTION
**Pull request by shubhajyoti-bagchi-groww**
fixes: https://github.com/argoproj/argo-rollouts/issues/3470

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-rollouts/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [x] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/) with a list of types and scopes found [here](https://github.com/argoproj/argo-rollouts/blob/master/.github/workflows/pr-title-check.yml), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [x] I've signed my commits with [DCO](https://github.com/argoproj/argoproj)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My builds are green. Try syncing with master if they are not. 
* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo-rollouts/blob/master/USERS.md).

### CODE REVIEW

**Comment by shubhajyoti-bagchi-groww** [comment]
Hi @OpenGuidou, thanks for the response

Right, this happens in cases whenever stable.AvailableReplicas > rollout.spec.Replicas

HPA is one way where stable.AvailableReplicas > rollout.spec.Replicas without any manual intervention
However, in the issue in which we faced, we had a need to reduce the number of replicas of the rollout which was in aborted state and came across the issue.

The e2e test here focuses on breaking the existing flow using one of the scenarios, without this fix. It kind of reproduces exactly what we faced.

**Review by OpenGuidou — APPROVED** [review]
LGTM, thanks !

**Comment by Eslam-mohammed-anwar** [comment]
we have a similar issue https://github.com/argoproj/argo-rollouts/issues/3470

**Review by zachaller — APPROVED** [review]

**Comment by Eslam-mohammed-anwar** [comment]
@zachaller when should it be released ?

**Pull request merged**
