### PR TITLE
chore: Update k8s version to 1.30

### PR DESCRIPTION
**Pull request by nikoshet**
Checklist:

* [X] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-rollouts/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [X] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/) with a list of types and scopes found [here](https://github.com/argoproj/argo-rollouts/blob/master/.github/workflows/pr-title-check.yml), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [X] I've signed my commits with [DCO](https://github.com/argoproj/argoproj)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My builds are green. Try syncing with master if they are not. 
* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo-rollouts/blob/master/USERS.md).

### CODE REVIEW

**Comment by zachaller** [comment]
We should remove on on the tail end like 1.26.

**Comment by mansing2** [comment]
Any plan in near future to support K8S v1.30. We want to upgrade the k8s and we are blocked.

**Comment by zachaller** [comment]
@mansing2 I would not let what clients Rollouts uses cause you to not upgrade your k8s cluster. As long as you do not use any of the new pod spec fields if there are any it will be ok we use very little k8s feature set. The only big one being the embedded pod spec into the rollout resource.

**Comment by blkperl** [comment]
This was resolved in https://github.com/argoproj/argo-rollouts/pull/3858

**Pull request closed without merging**
