### PR TITLE
feat(manifests): Add Age column to all CRD(s). Fixes #1511

### LINKED ISSUE #1511: Add age to `AnalysisRun` printer columns
# Summary

Add an `AGE` parameter to `AnalysisRun` printer columns for ease of viewing

# Use Cases

When debugging why a canary rolled back, doing a `kubectl get` of AnalysisRun returns just the name and status. While the name being composed of the replicaset makes things easier, I found that adding the Age parameter helps tremendously.

The only change we need to make is to add this to the `additonalPrinterColumns` in the CRD

```
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
```
 If you are interested in having this change, I'd love to contribute 😄 

I added this in my cluster's deployment and it helped the team a lot. This is how it looks:

image

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

### PR DESCRIPTION
**Pull request by yashmehrotra**
Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-rollouts/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [x] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [x] I've signed my commits with [DCO](https://github.com/argoproj/argoproj)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My builds are green. Try syncing with master if they are not. 
* [x] My organization is added to [USERS.md](https://github.com/argoproj/argo-rollouts/blob/master/USERS.md).

### CODE REVIEW

**Comment by yashmehrotra** [comment]
My organization is not added to the USERS.md, should I add it as part of this PR or create a separate PR ?

**Comment by yashmehrotra** [comment]
The Docker and E2E tests failed due to flakiness

Regarding the codegen, what should I do to make it green ? Since there is a change in the CRDs

**Comment by jessesuen** [comment]
> Regarding the codegen, what should I do to make it green ? Since there is a change in the CRDs

run `make codegen` and commit changes

> My organization is not added to the USERS.md, should I add it as part of this PR or create a separate PR ?

Thanks for adding! You can include as part of this PR or separate. Either is fine

**Comment by yashmehrotra** [comment]
@jessesuen Thanks, I have ran the `make codegen` and commited the changes. The CI should pass now

Have also added my org. in this PR itself.

**Comment by yashmehrotra** [comment]
@jessesuen Can you please take a look whenever you have time ?

**Review by jessesuen — APPROVED** [review]

**Pull request merged**
