### PR TITLE
fix: When Degraded state, canary-service doesn't have any endpoints

### PR DESCRIPTION
**Pull request by idurgakalyan**
When Degraded state, canary-service doesn't have any endpoints resulting in traefik unable to route requests in failed state.

Signed-off-by: Kalyan Inampudi <Kalyan.Inampudi@nike.com>

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-rollouts/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [x] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/) with a list of types and scopes found [here](https://github.com/argoproj/argo-rollouts/blob/master/.github/workflows/pr-title-check.yml), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [x] I've signed my commits with [DCO](https://github.com/argoproj/argoproj)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My builds are green. Try syncing with master if they are not. 
* [x] My organization is added to [USERS.md](https://github.com/argoproj/argo-rollouts/blob/master/USERS.md).

### CODE REVIEW

**Comment by zachaller** [comment]
I think this is also maybe related: https://github.com/argoproj/argo-rollouts/issues/1838

**Comment by idurgakalyan** [comment]
@zachaller Are you able to review?

**Comment by idurgakalyan** [comment]
E2E tests failed due to empty value mismatch, Is there anything else that needs to be done?

**Comment by idurgakalyan** [comment]
@zachaller Yes, this would work.

**Comment by idurgakalyan** [comment]
I can close this PR once https://github.com/argoproj/argo-rollouts/pull/2540 is merged.

**Comment by zachaller** [comment]
closed by: https://github.com/argoproj/argo-rollouts/pull/2540

**Pull request closed without merging**
