### PR TITLE
docs: mention supported versions

### PR DESCRIPTION
**Pull request by kostis-codefresh**
Signed-off-by: Kostis Kapelonis <kostis@codefresh.io>

Solves https://github.com/argoproj/argo-rollouts/issues/1939

Checklist:

* [X] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-rollouts/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [X] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [X] I've signed my commits with [DCO](https://github.com/argoproj/argoproj)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My builds are green. Try syncing with master if they are not. 
* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo-rollouts/blob/master/USERS.md).

### CODE REVIEW

**Review by rcontreras-te — COMMENTED** [review]
Thanks for the docs update @kostis-codefresh !

**Comment by zachaller** [comment]
This looks good I do think it makes sense to possibly do a table with versions that are supported as well so we can track the history of support, thoughts? If we do this we should also make note in the release docs https://github.com/argoproj/argo-rollouts/blob/master/docs/releasing.md about updating the table until we can possibly automate it.

**Comment by kostis-codefresh** [comment]
@zachaller FYI this is the same PR as Argo CD https://argo-cd.readthedocs.io/en/stable/operator-manual/installation/#supported-versions

It is bulletproof in the sense that it needs no updates at all.

**Comment by zachaller** [comment]
Yup that is fair it just makes it hard for the end users to know which versions where supported in the past without doing a whole bunch of date comparisons and looking at when argo rollouts was released and comparing it to when kubernetes was released to be able to say something like versions 1.1 of rollouts supported kubernetes versions 1.xx if we find that is to much a burden on the release to keep up to date I am fine either way nothing should block this PR. Just wanted feedback on if we felt that was useful.

**Review by zachaller — APPROVED** [review]

**Review by leoluz — APPROVED** [review]

**Pull request merged**
