### PR TITLE
fix: canary step analysis run wasn't terminated as keep running after promote action being called. Fixes #3220

### LINKED ISSUE #3220: Canary rollout: analysis run from previous step remains running after promotion
Checklist:

* [ ] I've included steps to reproduce the bug.
* [ ] I've included the version of argo rollouts.

**Describe the bug**

If canary rollout has 2 or more analysis steps one-by-one and you perform promotion on n-1 step with analysis. Analysis run of previous step will remain running while appropriate to new step won't be created.

**To Reproduce**

1. create canary rollout with 3 steps and 2 analysis steps one-by-one
```
- setWeight: 50
- analysis:
     templates:
     - templateName: test-template-a
- analysis:
     templates:
     - templateName: test-template-b     
```

2. try to call promote on `test-template-a` analysis step

**Expected behavior**

Old analysis run should be terminated and new one (for current step) should be created.

**Screenshots**
 \-

**Version**

tested on 1.5.0 and 1.6.3 

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

### PR DESCRIPTION
**Pull request by oleksandr-codefresh**
fixes #3220 

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-rollouts/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [ ] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/) with a list of types and scopes found [here](https://github.com/argoproj/argo-rollouts/blob/master/.github/workflows/pr-title-check.yml), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [ ] I've signed my commits with [DCO](https://github.com/argoproj/argoproj)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My builds are green. Try syncing with master if they are not. 
* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo-rollouts/blob/master/USERS.md).

### CODE REVIEW

**Comment by oleksandr-codefresh** [comment]
@zachaller was thinking about that, but don't have any unit tests for this method ATM)

**Comment by zachaller** [comment]
We do this function get's called via this https://github.com/argoproj/argo-rollouts/blob/master/rollout/analysis_test.go#L167 we spin up a controller there with a fake k8s client which will reconcile which ends up calling that function eventually.

**Comment by oleksandr-codefresh** [comment]
ok, will try to add

**Comment by oleksandr-codefresh** [comment]
@zachaller added

**Comment by oleksandr-codefresh** [comment]
@zachaller Hi, could you pls take a look?

**Pull request merged**
