### PR TITLE
fix: missing array type in the CRD rollout's spec volumes

### LINKED ISSUE #1721: Adding a volume to a rollout breaks it
## Summary 

What happened/what you expected to happen?
I added a volume to the sample rollout, it broke. I expected it to work. Converting it to a deployment works as expected

```
  apiVersion: argoproj.io/v1alpha1
  kind: Rollout
  metadata:
    name: rollouts-demo
  spec:
    replicas: 5
    strategy:
      canary:
        steps:
        - setWeight: 20
        - pause: {}
        - setWeight: 40
        - pause: {duration: 10}
    revisionHistoryLimit: 2
    selector:
      matchLabels:
        app: rollouts-demo
    template:
      metadata:
        labels:
          app: rollouts-demo
      spec:
        containers:
        - name: rollouts-demo
          image: argoproj/rollouts-demo:blue
          ports:
          - name: http
            containerPort: 8080
            protocol: TCP
          resources:
            requests:
              memory: 32Mi
              cpu: 5m
        volumes:
        - name: cache-volume
          emptyDir: {}
```

## Diagnostics

What version of Argo Rollouts are you running?

quay.io/argoproj/argo-rollouts:latest

I am running Kubernetes v1.23.0 so needed the latest tag for the `ingress-api-version` flag

```
time="2021-12-17T03:31:20Z" level=info msg="Patched conditions: {\"status\":{\"conditions\":[{\"lastTransitionTime\":\"2021-12-17T03:31:20Z\",\"lastUpdateTime\":\"2021-12-17T03:31:20Z\",\"message\":\"The Rollout \\\"rollouts-demo\\\" is invalid: spec.template.spec.volumes[0].name: Required value\",\"reason\":\"InvalidSpec\",\"status\":\"True\",\"type\":\"InvalidSpec\"}],\"message\":\"InvalidSpec: The Rollout \\\"rollouts-demo\\\" is invalid: spec.template.spec.volumes[0].name: Required value\",\"observedGeneration\":\"1\",\"phase\":\"Degraded\"}}" generation=1 namespace=default resourceVersion=427384 rollout=rollouts-demo

```

Dumping out the YAML, it's clear the volumes node has been completely wiped:

```
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"argoproj.io/v1alpha1","kind":"Rollout","metadata":{"annotations":{},"name":"rollouts-demo","namespace":"default"},"spec":{"replicas":5,"revisionHistoryLimit":2,"selector":{"matchLabels":{"app":"rollouts-demo"}},"strategy":{"canary":{"steps":[{"setWeight":20},{"pause":{}},{"setWeight":40},{"pause":{"duration":10}},{"setWeight":60},{"pause":{"duration":10}},{"setWeight":80},{"pause":{"duration":10}}]}},"template":{"metadata":{"labels":{"app":"rollouts-demo"}},"spec":{"containers":[{"image":"argoproj/rollouts-demo:blue","name":"rollouts-demo","ports":[{"containerPort":8080,"name":"http","protocol":"TCP"}],"resources":{"requests":{"cpu":"5m","memory":"32Mi"}}}],"volumes":[{"emptyDir":{},"name":"cache-volume"}]}}}}
  creationTimestamp: "2021-12-17T03:37:11Z"
  generation: 1
  name: rollouts-demo
  namespace: default
  resourceVersion: "428224"
  uid: cd07791c-abe9-47b6-8b92-b5c2aad4acbb
spec:
  replicas: 5
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rollouts-demo
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {}
      - setWeight: 40
      - pause:
          duration: 10
      - setWeight: 60
      - pause:
          duration: 10
      - setWeight: 80
      - pause:
          duration: 10
  template:
    metadata:
      labels:
        app: rollouts-demo
    spec:
      containers:
      - image: argoproj/rollouts-demo:blue
        name: rollouts-demo
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 5m
            memory: 32Mi
      volumes:
      - {}
status:
  conditions:
  - lastTransitionTime: "2021-12-17T03:37:11Z"
    lastUpdateTime: "2021-12-17T03:37:11Z"
    message: 'The Rollout "rollouts-demo" is invalid: spec.template.spec.volumes[0].name:
      Required value'
    reason: InvalidSpec
    status: "True"
    type: InvalidSpec
  message: 'InvalidSpec: The Rollout "rollouts-demo" is invalid: spec.template.spec.volumes[0].name:
    Required value'
  observedGeneration: "1"
  phase: Degraded

```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

### PR DESCRIPTION
**Pull request by huikang**
Signed-off-by: Hui Kang <hui.kang@salesforce.com>

fix #1721 

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-rollouts/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [ ] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [ ] I've signed my commits with [DCO](https://github.com/argoproj/argoproj)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My builds are green. Try syncing with master if they are not. 
* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo-rollouts/blob/master/USERS.md).

### CODE REVIEW

**Comment by jessesuen** [comment]
@huikang thanks for fixing this. Do you think we could modify an e2e test to have a volume so that we catch this in the future?

**Comment by huikang** [comment]
> @huikang thanks for fixing this. Do you think we could modify an e2e test to have a volume so that we catch this in the future?

Sure, let me look into this and get back to you later.

**Comment by huikang** [comment]
@jessesuen , checking that the volumes field is an array seems a feature starting from k8s release 1.23.1.

For k8s version v1.21.1, v1.22.1, the original `install.yaml` works fine, although it misses the array type for the volumes. 
Only k8s v1.23.1 reports the following error with the wrong rollout crd:

```
"The Rollout \"rollouts-demo\" is invalid: spec.template.spec.volumes[0].name: Required value"
  namespace=default rollout=rollouts-demo
```

Since the existing git CI of this repo defaults to v1.22.1, one solution would be to upgrade the version to v1.23.1 
https://github.com/argoproj/argo-rollouts/blob/c291d2de762790a43df66257d87046131b4fc7a4/.github/workflows/e2e.yaml#L25-L32

and then add `volumes` to one of the existing e2e rollout.

What do you think?

**Review by jessesuen — APPROVED** [review]
We can add e2e test as a separate PR which conditionally skips depending on the k8s version it is running against.

**Pull request merged**
