### PR TITLE
feat: kustomize rollout: add openapi to doc and examples

### LINKED ISSUE #1210: genenerate x-kubernetes-patch-merge-key and x-kubernetes-patch-strategy
# Summary

Kustomize 4 has finally has a mechanism to teach it how to SMP custom resources. See:

* https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/openapi/
* https://github.com/kubernetes-sigs/kustomize/issues/2825
* https://github.com/kubernetes-sigs/kustomize/issues/2339
* https://github.com/kubernetes-sigs/kustomize/blob/master/examples/customOpenAPIschema.md

 In order for kustomize to patch CRDs properly, we need to publish openAPI schema containing the following metadata in the Rollout CRD definitions.
* x-kubernetes-patch-merge-key
* x-kubernetes-patch-strategy

This will lower the barrier of entry to Rollouts and cause less surprising behavior.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

### PR DESCRIPTION
**Pull request by huikang**
- openAPI schema for kustomize rollout

Signed-off-by: Hui Kang <hui.kang@salesforce.com>

close #1210 

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-rollouts/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [ ] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [ ] I've signed my commits with [DCO](https://github.com/argoproj/argoproj)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My builds are green. Try syncing with master if they are not. 
* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo-rollouts/blob/master/USERS.md).

### CODE REVIEW

**Comment by jessesuen** [comment]
@huikang - did you hand code the `rollout_cr_schema.json` file? Is there not a way to auto-generate it?

**Comment by huikang** [comment]
Hi, @jessesuen , yeah, I handcoded `rollout_cr_schema.json` by adapting from [this example](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/openapi/). It seems to me the openapi data is flexible to customize different use case; I have not found any way to auto-generate the content from the k8s type. Please let me know  if you are aware of any approach.

**Comment by jessesuen** [comment]
This file:
https://github.com/argoproj/argo-rollouts/blob/master/pkg/apiclient/rollout/rollout.swagger.json

is autogenerated. I thought something similar would need to be done for Rollouts but with the SMP keys

**Comment by huikang** [comment]
> This file:
> https://github.com/argoproj/argo-rollouts/blob/master/pkg/apiclient/rollout/rollout.swagger.json
> 
> is autogenerated. I thought something similar would need to be done for Rollouts but with the SMP keys

Thanks. Let me look into the options of the open-api tool.

**Comment by huikang** [comment]
Hi, @jessesuen , just want to make sure I understand the problem correctly: the problem is that the content in https://github.com/argoproj/argo-rollouts/blob/master/pkg/apiclient/rollout/rollout.swagger.json misses some `x-kubernetes-patch-merge-key` and `x-kubernetes-patch-strategy` for certain properties. For example, in the definition of 

```
type PodSpec struct {
  Containers []Container `json:"containers" patchStrategy:"merge" patchMergeKey:"name" ...`

```
the `containers` has the patchStrategy and patchMergeKey, however, the generated `rollout.swagger.json` misses `x-kubernetes-patch-merge-key` and `x-kubernetes-patch-strategy`. 

So we need to figure our how to let https://github.com/argoproj/argo-rollouts/blob/e3dc6af9e04d9b5883dd7f3a2b823948d026e73e/Makefile#L50 attach these annotations in the generated json file.

Is my understanding correct? Thanks.

**Comment by jessesuen** [comment]
Yes, that is correct. The goal is for kustomize 4 to be able to patch rollouts in the same way as deployments. If we can achieve this via automation that would be ideal, but not sure if that is possible.

**Comment by huikang** [comment]
> Yes, that is correct. The goal is for kustomize 4 to be able to patch rollouts in the same way as deployments. If we can achieve this via automation that would be ideal, but not sure if that is possible.

Following is my findings:

1. This is how k8s api is exposed as a json file: 

https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/hack/update-openapi-spec.sh#L101

2. In addition, I found that the `kustomize openapi fetch` returns 

```json
    "io.argoproj.v1alpha1.Rollout": {
      "properties": {
        "apiVersion": {
          "type": "string"
        },
        "kind": {
          "type": "string"
        },
        "metadata": {
          "$ref": "#/definitions/io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta",
          "description": "Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata"
        },
        "spec": {
            "template": {
              "properties": {
                "metadata": {
                  "properties": {
                    "annotations": {
                      "additionalProperties": {
                        "type": "string"

```

If I change the key "template" to 

```yaml
"template": {
              "$ref": "#/definitions/io.k8s.api.core.v1.PodTemplateSpec"
            }
```

The SMP would work. Not sure why the original one does not use the reference definition.

**Comment by alexmt** [comment]
@huikang , I think I found a way to generate schema. There is no out of the box generator unfortunatelly so I had to write more go code in gen-crd-spec/main.go.

We tests and documentation changes from your PR so I've sent PR to your fork: https://github.com/huikang/argo-rollouts/pull/1 . Once it is merged this PR should be complete. Can you please take a look?

**Comment by huikang** [comment]
> @huikang , I think I found a way to generate schema. There is no out of the box generator unfortunatelly so I had to write more go code in gen-crd-spec/main.go.
> 
> We tests and documentation changes from your PR so I've sent PR to your fork: [huikang#1](https://github.com/huikang/argo-rollouts/pull/1) . Once it is merged this PR should be complete. Can you please take a look?

Sounds good. Thanks, @alexmt !

**Comment by huikang** [comment]
Hi, @alexmt , I have merged your commit and cleaned up the PR a bit. However, when the new command failed due to the following error

```
go run ./hack/gen-crd-spec/main.go
panic: Version string empty

goroutine 1 [running]:
main.checkErr(...)
	/Users/hui.kang/go/src/github.com/huikang/argo-rollouts-backup2/hack/gen-crd-spec/main.go:287
main.main()
	/Users/hui.kang/go/src/github.com/huikang/argo-rollouts-backup2/hack/gen-crd-spec/main.go:467 +0x5d3
exit status 2
```

Could you take a look? Thanks.

**Review by alexmt — APPROVED** [review]
LGTM!

**Review by jessesuen — APPROVED** [review]

**Pull request merged**
