### PR TITLE
feat(analysis): add Apache SkyWalking as metrics provider

### PR DESCRIPTION
**Pull request by kezhenxu94**
Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-rollouts/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [x] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/) with a list of types and scopes found [here](https://github.com/argoproj/argo-rollouts/blob/master/.github/workflows/pr-title-check.yml), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [x] I've signed my commits with [DCO](https://github.com/argoproj/argoproj)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My builds are green. Try syncing with master if they are not. 
* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo-rollouts/blob/master/USERS.md).

### CODE REVIEW

**Comment by kezhenxu94** [comment]
Tests seem to be unstable, it can pass in my local machine

**Comment by harikrongali** [comment]
https://github.com/argoproj/argo-rollouts/pull/2514 solves supporting additional metrics providers without adding them to rollout source. @zachaller can confirm if we need this PR?

**Comment by zachaller** [comment]
> #2514 solves supporting additional metrics providers without adding them to rollout source. @zachaller can confirm if we need this PR?

Even though plugin system has just been merged it also is not 100% complete yet though it is close. I still do plan and think that merging this is the correct thing to do for a few reasons. One being that a good majority of users of this metric provider will be APISIX traffic router users the two projects are both under the apache foundation and share the same user base. 

We have already merged APISIX before any plugin systems where in place and this PR was also submitted way before any plugin systems where in place as well. Therefore I do think it makes sense to allow this PR through however this will probably be the last one that goes straight into the main project. 

I do think though that even with plugins having some form of graduation type system in place where plugins can gain enough traction and or meet some requirements that they move into "core" project however all that has not really been decided yet.

**Review by zachaller — APPROVED** [review]

**Comment by kezhenxu94** [comment]
@zachaller thank you for helping to resolve the conflicts and merging the pr!

**Pull request merged**
