### PR TITLE
feat: Allow Traffic shaping through header based routing ALB

### PR DESCRIPTION
**Pull request by perenesenko**
Signed-off-by: Andrii Perenesenko <andrii.perenesenko@gmail.com>

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-rollouts/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [x] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [x] I've signed my commits with [DCO](https://github.com/argoproj/argoproj)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My builds are green. Try syncing with master if they are not. 
* [x] My organization is added to [USERS.md](https://github.com/argoproj/argo-rollouts/blob/master/USERS.md).

### CODE REVIEW

**Comment by ssanders1449** [comment]
@perenesenko - Why did you close this PR? We have a sceario where argo-rollouts is controlling an ALB, but we want requests from out test clients to always go to canary pods. Is there another way to do this?

**Comment by zachaller** [comment]
@ssanders1449 this was done in https://github.com/argoproj/argo-rollouts/pull/2214

**Comment by chengxiaogong** [comment]
Can you provide an example like this? There were some issues with my testing here

**Comment by Borisakov** [comment]
Is there any documentation for it?
Thanks!

**Pull request closed without merging**
