### PR TITLE
Fix: Failed analysis to degrade rollout when multiple metrics are analyzed

### PR DESCRIPTION
**Pull request by harikrongali**
Checklist:
Fixes behavior https://github.com/argoproj/argo-rollouts/issues/1411 although issue is reproducible in 1.0.6 release because of fix https://github.com/argoproj/argo-rollouts/pull/1407 
* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-rollouts/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [ ] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [ ] I've signed my commits with [DCO](https://github.com/argoproj/argoproj)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My builds are green. Try syncing with master if they are not. 
* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo-rollouts/blob/master/USERS.md).

### CODE REVIEW

**Review by jessesuen — APPROVED** [review]

**Review by alexmt — APPROVED** [review]
LGTM

**Comment by jessesuen** [comment]
@harikrongali I dismissed my earlier review because I remember there was a reason the code was written this way and I want to make sure we dont break it.

I recall that we did not want to mark the AnalysisRun completed until everything which needed to do was completed. This includes stopping in-flight jobs. Can you verify the following scenario:
1. start an AnalysisRun with multiple Job metrics, one that sleeps forever, and one that has an initialDelaySeconds of 9999. 
2. terminate the AnalysisRun after the job is created

Will the AnalysisRun stop the in-flight job?

**Comment by harikrongali** [comment]
@jessesuen i will validate asap

**Comment by jessesuen** [comment]
Nevermind. I think we are good. This is the scenario I was concerned about:

```yaml
kind: AnalysisRun
apiVersion: argoproj.io/v1alpha1
metadata:
  generateName: analysis-run-job-
spec:
  metrics:
  - name: dont-finish
    provider:
      job:
        spec:
          template:
            spec:
              containers:
              - name: sleep
                image: nginx:1.19-alpine
                command: [sleep, "999999"]
              restartPolicy: Never
          backoffLimit: 0
  - name: fail
    provider:
      job:
        spec:
          template:
            spec:
              containers:
              - name: sleep
                image: nginx:1.19-alpine
                command: [sh, -c, "sleep 10 && exit 1"]
              restartPolicy: Never
          backoffLimit: 0
  - name: dont-start
    initialDelay: 24h
    provider:
      job:
        spec:
          template:
            spec:
              containers:
              - name: sleep
                image: nginx:1.19-alpine
                command: [sh, -c, "exit 0"]
              restartPolicy: Never
          backoffLimit: 0
```

I verified nothing is left running when the second metric fails.

**Pull request merged**
