### PR TITLE
docs: remove note about ambassador-api-version-flag

### PR DESCRIPTION
**Pull request by thedevelopnik**
I went through an Ambassador Edge Stack upgrade a few months ago, going from 1.x to 3.x. Got stuck for quite awhile because it looks (from the tests) like the v3alpha1 API version is now the default. Passing the flag `--ambassador-api-version x.getambassador.io/v3alpha1` as noted in the docs actually breaks the installation. This removes that part of the special instructions.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-rollouts/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [x] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/) with a list of types and scopes found [here](https://github.com/argoproj/argo-rollouts/blob/master/.github/workflows/pr-title-check.yml), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [x] I've signed my commits with [DCO](https://github.com/argoproj/argoproj)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My builds are green. Try syncing with master if they are not. 
* [x] My organization is added to [USERS.md](https://github.com/argoproj/argo-rollouts/blob/master/USERS.md).

### CODE REVIEW

**Comment by zachaller** [comment]
Based on the defaults https://github.com/argoproj/argo-rollouts/blob/master/utils/defaults/defaults.go#L52 I think there is just a type with the `x.getambassador.io/v3alpha1` should just be `getambassador.io/v3alpha1` and based on https://www.getambassador.io/docs/edge-stack/latest/about/changes-2.x/#1-configuration-api-version-getambassadoriov3alpha1

**Comment by thedevelopnik** [comment]
@zachaller I tested that approach using the api version without `x.` and it works, so I've updated this PR. Thanks!

**Comment by zachaller** [comment]
Perfect thanks you for testing that and making the correction! If you could fix the DCO will get it merged.

**Review by zachaller — APPROVED** [review]

**Comment by thedevelopnik** [comment]
@zachaller This is my first time doing signoff, and I merged the base branch back into mine. Now there are somehow more changes than just mine in the mix, so I'm pretty sure I worked myself into a hole here. Since the change is so small I'm going to close this PR and open a new one. Apologies!

**Comment by zachaller** [comment]
No problem will look for new PR

**Pull request closed without merging**
