### PR TITLE
fix: analysis information box #2530 

### PR DESCRIPTION
**Pull request by schakrad**
fixes: #2530 

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-rollouts/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [ ] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/) with a list of types and scopes found [here](https://github.com/argoproj/argo-rollouts/blob/master/.github/workflows/pr-title-check.yml), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [x] I've signed my commits with [DCO](https://github.com/argoproj/argoproj)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My builds are green. Try syncing with master if they are not. 
* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo-rollouts/blob/master/USERS.md).

Before

Screen Shot 2023-02-07 at 11 20 46 PM

After

Screen Shot 2023-02-07 at 11 20 19 PM

### CODE REVIEW

**Comment by zachaller** [comment]
@schakrad can you run `make codegen`

**Comment by zachaller** [comment]
@schakrad no need to make codegen yet there was some upstream issue causing issues

**Review by zachaller — APPROVED** [review]

**Comment by Hronom** [comment]
Hey, when this will be available? I'm on 1.4.1 and issue still there:
image

**Comment by zachaller** [comment]
It just did not get cherry picked back onto 1.4.1 it will be fixed in 1.5 which is expected to release end of March.

**Pull request merged**
