### PR TITLE
fix: rollout should skip timeout when paused

### PR DESCRIPTION
**Pull request by wangli1030**
fix for issue https://github.com/argoproj/argo-rollouts/issues/3534
Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-rollouts/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [x] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/) with a list of types and scopes found [here](https://github.com/argoproj/argo-rollouts/blob/master/.github/workflows/pr-title-check.yml), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [x] I've signed my commits with [DCO](https://github.com/argoproj/argoproj)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My builds are green. Try syncing with master if they are not.

### CODE REVIEW

**Comment by wangli1030** [comment]
Hi @zachaller, could you help to review this PR? This issue really trouble us when user did not promote Rollouts in certain timeframe(progressDeadlineSeconds) and controller will mark it as timeout, hence ArgoCD will mark it as `Sync Failed`. Also in [Rollout spec](https://argo-rollouts.readthedocs.io/en/stable/features/specification/), it clearly states that ` # Note that progress will not be estimated during the time a rollout is paused.`. Let me know if you need more proof on this. Thank you.

**Comment by zachaller** [comment]
Can you add a unit or e2e test for this?

**Comment by wangli1030** [comment]
> Can you add a unit or e2e test for this?

Sure, will add it.

**Comment by wangli1030** [comment]
Hi @zachaller , UTs have been added. Please review it. Thank you.

**Comment by kishoregv** [comment]
Hey @zachaller,

I wanted to gently follow up on this pull request. I understand that you have many priorities to juggle, but I was hoping to get some feedback or an update on the status of this PR. If there are any changes or improvements needed, I'd be more than happy to address them. 

Thank you for your time and consideration. I look forward to hearing from you.

**Review by zachaller — APPROVED** [review]

**Pull request merged**
