### PR TITLE
feat: Create new table view in Rollouts dashboard

### PR DESCRIPTION
**Pull request by phclark**
Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-rollouts/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [x] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/) with a list of types and scopes found [here](https://github.com/argoproj/argo-rollouts/blob/master/.github/workflows/pr-title-check.yml), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [ ] I've signed my commits with [DCO](https://github.com/argoproj/argoproj)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My builds are green. Try syncing with master if they are not. 
* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo-rollouts/blob/master/USERS.md).

### CODE REVIEW

**Comment by zachaller** [comment]
Can you get the DCO to pass? You will probably need to force push to rewrite history so all commits have DCO signature

**Comment by phclark** [comment]
I thought I had this fixed, honestly. The rebase worked on my other PR but doesn't seem to fix it for this one. I've rebased a couple times already, trying to get the DCO check to pass to no avail. There are many merge conflicts when I do this, is there an easier approach? Perhaps starting with a fresh branch now that I've enabled sign off on commits?

**Comment by zachaller** [comment]
Yea without rewriting git history so every commit is signed the other maybe simpler thing is do what you said create a new branch and get these changes there so that there is a single commit that is signed

**Comment by zachaller** [comment]
Something with this branch is funny as well I see there are like 190 commits so history has diverged somewhere or something

**Comment by phclark** [comment]
Closing this PR in favor of https://github.com/argoproj/argo-rollouts/pull/3118

**Pull request closed without merging**
