### PR TITLE
docs(example): interval requires count

### PR DESCRIPTION
**Pull request by meeech**
docs(example): moved other count up next to interval for visibility

fixes: #2691

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-rollouts/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [x] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/) with a list of types and scopes found [here](https://github.com/argoproj/argo-rollouts/blob/master/.github/workflows/pr-title-check.yml), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [x] I've signed my commits with [DCO](https://github.com/argoproj/argoproj)
* [ n/a ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My builds are green. Try syncing with master if they are not. 
* [ n/a ] My organization is added to [USERS.md](https://github.com/argoproj/argo-rollouts/blob/master/USERS.md).

### CODE REVIEW

**Review by agrawroh — CHANGES_REQUESTED** [review]
I don't think you need `count` when interval is specified. The docs clearly say:

_"If both interval and count are omitted, the effective count is 1. If only interval is specified, metric runs indefinitely."_

I would expect the analysis to keep running indefinitely in absence of the `count`.

**Comment by meeech** [comment]
@agrawroh 1.4.1
Does it make sense for it to run indefinitely when it's an inline step? Then the rollout would never complete? So I suppose the error makes sense in that we wouldnt want people to accidentally put themselves in a rollout that would never progress? Or would the only way out be a manual promote?

**Comment by agrawroh** [comment]
> @agrawroh 1.4.1 Does it make sense for it to run indefinitely when it's an inline step? Then the rollout would never complete? So I suppose the error makes sense in that we wouldnt want people to accidentally put themselves in a rollout that would never progress? Or would the only way out be a manual promote?
> 
> Could be the docs are a bit out of date - I could update the pr to update to the docs you pointed out - maybe we need them to be more specific - making the distinction between inline vs background analysis.
> 
> In any case, I would defer to the code over the docs - and assume docs need updating.

You definitely need one of `interval` or `count` but I'm not convinced that we need to specify both. For example, if I just specify the `interval` with some success/failure counts, then I'd like the analysis to run and take as many measurements as possible and either fail or succeed based on the specified conditions. I can optionally specify the `count` to only take N measurements but it shouldn't be required if I have already specified the `interval`.

**Review by zachaller — APPROVED** [review]

**Comment by zachaller** [comment]
The reason count is needed with interval here is because in the examples the way this template is used is in an inline step which has to have an end, otherwise the step would never complete. In background analysis you need interval but not count because it will just run till the rollout is done. I agree docs could probably be updated around this.

**Comment by zachaller** [comment]
This PR just fixes the case for how this template is used within the examples folder.

**Pull request merged**
