### PR TITLE
chore: pin sys module in go.mod to resolve a fatal runtime execution in go 1.17

### LINKED ISSUE #1693: Fatal runtime execution using go 1.17
## Summary 

What happened/what you expected to happen?

go run cmd/rollouts-controller/main.go 

```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb01dfacedebac1e pc=0x7fff20353c9e]

runtime stack:
runtime: unexpected return pc for runtime.sigpanic called from 0x7fff20353c9e
stack: frame={sp:0x7ffeefbff538, fp:0x7ffeefbff588} stack=[0x7ffeefb805d8,0x7ffeefbff640)
0x00007ffeefbff438:  0x01007ffeefbff458  0x0000000000000004 
0x00007ffeefbff448:  0x000000000000001f  0x00007fff20353c9e 
0x00007ffeefbff458:  0x0b01dfacedebac1e  0x0000000000000001 
0x00007ffeefbff468:  0x0000000004036c91 <runtime.throw+0x0000000000000071>  0x00007ffeefbff508 
0x00007ffeefbff478:  0x0000000005ec043c  0x00007ffeefbff4c0 
0x00007ffeefbff488:  0x0000000004036f48 <runtime.fatalthrow.func1+0x0000000000000048>  0x00000000074d7320 
0x00007ffeefbff498:  0x0000000000000001  0x0000000000000001 
0x00007ffeefbff4a8:  0x00007ffeefbff508  0x0000000004036c91 <runtime.throw+0x0000000000000071> 
0x00007ffeefbff4b8:  0x00000000074d7320  0x00007ffeefbff4f8 
0x00007ffeefbff4c8:  0x0000000004036ed0 <runtime.fatalthrow+0x0000000000000050>  0x00007ffeefbff4d8 
0x00007ffeefbff4d8:  0x0000000004036f00 <runtime.fatalthrow.func1+0x0000000000000000>  0x00000000074d7320 
0x00007ffeefbff4e8:  0x0000000004036c91 <runtime.throw+0x0000000000000071>  0x00007ffeefbff508 
0x00007ffeefbff4f8:  0x00007ffeefbff528  0x0000000004036c91 <runtime.throw+0x0000000000000071> 
0x00007ffeefbff508:  0x00007ffeefbff510  0x0000000004036cc0 <runtime.throw.func1+0x0000000000000000> 
0x00007ffeefbff518:  0x0000000005ed9fd8  0x000000000000002a 
0x00007ffeefbff528:  0x00007ffeefbff578  0x000000000404c976 <runtime.sigpanic+0x0000000000000396> 
0x00007ffeefbff538: <0x0000000005ed9fd8  0x0000000006d25dd8 
0x00007ffeefbff548:  0x00007ffeefbff5b8  0x0000000004028e46 <runtime.(*mheap).allocSpan+0x0000000000000546> 
0x00007ffeefbff558:  0x0000000004068101 <runtime.goexit+0x0000000000000001>  0x0000000000000000 
0x00007ffeefbff568:  0x000000c000bfffe0  0x000000c000bfffe8 
0x00007ffeefbff578:  0x00007ffeefbff5c0 !0x00007fff20353c9e 
0x00007ffeefbff588: >0x00007ffeefbff5c0  0x00000000073e0000 
0x00007ffeefbff598:  0x000000000000048e  0x00000000047851e5 <golang.org/x/sys/unix.libc_ioctl_trampoline+0x0000000000000005> 
0x00007ffeefbff5a8:  0x0000000004069fbf <runtime.syscall+0x000000000000001f>  0x000000c000bfee30 
0x00007ffeefbff5b8:  0x00007ffeefbff600  0x000000c000bfee00 
0x00007ffeefbff5c8:  0x0000000004067e10 <runtime.asmcgocall+0x0000000000000070>  0x0000000000000001 
0x00007ffeefbff5d8:  0x0000000004004c00 <internal/abi.(*IntArgRegBitmap).Set+0x0000000000000040>  0x4c00000000001018 
0x00007ffeefbff5e8:  0x0000000000000000  0x000000000750caf8 
0x00007ffeefbff5f8:  0x0000000000001228  0x000000c0000001a0 
0x00007ffeefbff608:  0x0000000004065f29 <runtime.systemstack+0x0000000000000049>  0x0000000000000004 
0x00007ffeefbff618:  0x00000000061f27d8  0x00000000074d7320 
0x00007ffeefbff628:  0x00007ffeefbff678  0x0000000004065e25 <runtime.mstart+0x0000000000000005> 
0x00007ffeefbff638:  0x0000000004065ddd <runtime.rt0_go+0x000000000000013d> 
runtime.throw({0x5ed9fd8, 0x6d25dd8})
	/usr/local/go/src/runtime/panic.go:1198 +0x71
runtime: unexpected return pc for runtime.sigpanic called from 0x7fff20353c9e
stack: frame={sp:0x7ffeefbff538, fp:0x7ffeefbff588} stack=[0x7ffeefb805d8,0x7ffeefbff640)
0x00007ffeefbff438:  0x01007ffeefbff458  0x0000000000000004 
0x00007ffeefbff448:  0x000000000000001f  0x00007fff20353c9e 
0x00007ffeefbff458:  0x0b01dfacedebac1e  0x0000000000000001 
0x00007ffeefbff468:  0x0000000004036c91 <runtime.throw+0x0000000000000071>  0x00007ffeefbff508 
0x00007ffeefbff478:  0x0000000005ec043c  0x00007ffeefbff4c0 
0x00007ffeefbff488:  0x0000000004036f48 <runtime.fatalthrow.func1+0x0000000000000048>  0x00000000074d7320 
0x00007ffeefbff498:  0x0000000000000001  0x0000000000000001 
0x00007ffeefbff4a8:  0x00007ffeefbff508  0x0000000004036c91 <runtime.throw+0x0000000000000071> 
0x00007ffeefbff4b8:  0x00000000074d7320  0x00007ffeefbff4f8 
0x00007ffeefbff4c8:  0x0000000004036ed0 <runtime.fatalthrow+0x0000000000000050>  0x00007ffeefbff4d8 
0x00007ffeefbff4d8:  0x0000000004036f00 <runtime.fatalthrow.func1+0x0000000000000000>  0x00000000074d7320 
0x00007ffeefbff4e8:  0x0000000004036c91 <runtime.throw+0x0000000000000071>  0x00007ffeefbff508 
0x00007ffeefbff4f8:  0x00007ffeefbff528  0x0000000004036c91 <runtime.throw+0x0000000000000071> 
0x00007ffeefbff508:  0x00007ffeefbff510  0x0000000004036cc0 <runtime.throw.func1+0x0000000000000000> 
0x00007ffeefbff518:  0x0000000005ed9fd8  0x000000000000002a 
0x00007ffeefbff528:  0x00007ffeefbff578  0x000000000404c976 <runtime.sigpanic+0x0000000000000396> 
0x00007ffeefbff538: <0x0000000005ed9fd8  0x0000000006d25dd8 
0x00007ffeefbff548:  0x00007ffeefbff5b8  0x0000000004028e46 <runtime.(*mheap).allocSpan+0x0000000000000546> 
0x00007ffeefbff558:  0x0000000004068101 <runtime.goexit+0x0000000000000001>  0x0000000000000000 
0x00007ffeefbff568:  0x000000c000bfffe0  0x000000c000bfffe8 
0x00007ffeefbff578:  0x00007ffeefbff5c0 !0x00007fff20353c9e 
0x00007ffeefbff588: >0x00007ffeefbff5c0  0x00000000073e0000 
0x00007ffeefbff598:  0x000000000000048e  0x00000000047851e5 <golang.org/x/sys/unix.libc_ioctl_trampoline+0x0000000000000005> 
0x00007ffeefbff5a8:  0x0000000004069fbf <runtime.syscall+0x000000000000001f>  0x000000c000bfee30 
0x00007ffeefbff5b8:  0x00007ffeefbff600  0x000000c000bfee00 
0x00007ffeefbff5c8:  0x0000000004067e10 <runtime.asmcgocall+0x0000000000000070>  0x0000000000000001 
0x00007ffeefbff5d8:  0x0000000004004c00 <internal/abi.(*IntArgRegBitmap).Set+0x0000000000000040>  0x4c00000000001018 
0x00007ffeefbff5e8:  0x0000000000000000  0x000000000750caf8 
0x00007ffeefbff5f8:  0x0000000000001228  0x000000c0000001a0 
0x00007ffeefbff608:  0x0000000004065f29 <runtime.systemstack+0x0000000000000049>  0x0000000000000004 
0x00007ffeefbff618:  0x00000000061f27d8  0x00000000074d7320 
0x00007ffeefbff628:  0x00007ffeefbff678  0x0000000004065e25 <runtime.mstart+0x0000000000000005> 
0x00007ffeefbff638:  0x0000000004065ddd <runtime.rt0_go+0x000000000000013d> 
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:719 +0x396

goroutine 1 [syscall]:
syscall.syscall(0x47851e0, 0x2, 0x40487413, 0xc000bfeec0)
	/usr/local/go/src/runtime/sys_darwin.go:22 +0x3b fp=0xc000bfee30 sp=0xc000bfee10 pc=0x40649db
syscall.syscall(0xc000bfeeb8, 0x10, 0xc0003cf600, 0xc0003cf700)
	<autogenerated>:1 +0x26 fp=0xc000bfee78 sp=0xc000bfee30 pc=0x406a786
golang.org/x/sys/unix.ioctl(0x4d18e7b, 0x5afe680, 0xc00059d200)
	/Users/hui.kang/go/src/github.com/huikang/argo-rollouts-backup2/vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.go:690 +0x39 fp=0xc000bfeea8 sp=0xc000bfee78 pc=0x4784d39
golang.org/x/sys/unix.IoctlGetTermios(...)
	/Users/hui.kang/go/src/github.com/huikang/argo-rollouts-backup2/vendor/golang.org/x/sys/unix/ioctl.go:73
github.com/sirupsen/logrus.isTerminal(0xc000bff488)
	/Users/hui.kang/go/src/github.com/huikang/argo-rollouts-backup2/vendor/github.com/sirupsen/logrus/terminal_check_bsd.go:11 +0x50 fp=0xc000bfef18 sp=0xc000bfeea8 pc=0x4d0af30
github.com/sirupsen/logrus.checkIfTerminal({0x62174a0, 0xc000010020})
	/Users/hui.kang/go/src/github.com/huikang/argo-rollouts-backup2/vendor/github.com/sirupsen/logrus/terminal_check_notappengine.go:13 +0x75 fp=0xc000bfef30 sp=0xc000bfef18 pc=0x4d0afd5
github.com/sirupsen/logrus.(*TextFormatter).init(0xc000201680, 0x304f31f8)
	/Users/hui.kang/go/src/github.com/huikang/argo-rollouts-backup2/vendor/github.com/sirupsen/logrus/text_formatter.go
```

## Diagnostics

What version of Argo Rollouts are you running?

master

```
# Paste the logs from the rollout controller

# Logs for the entire controller:
kubectl logs -n argo-rollouts deployment/argo-rollouts

# Logs for a specific rollout:
kubectl logs -n argo-rollouts deployment/argo-rollouts | grep rollout=<ROLLOUTNAME>
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

### PR DESCRIPTION
**Pull request by huikang**
Signed-off-by: Hui Kang <hui.kang@salesforce.com>

close #1693 

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-rollouts/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [ ] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [ ] I've signed my commits with [DCO](https://github.com/argoproj/argoproj)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My builds are green. Try syncing with master if they are not. 
* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo-rollouts/blob/master/USERS.md).

### CODE REVIEW

**Review by jessesuen — APPROVED** [review]

**Comment by jessesuen** [comment]
Some reason codegen verify is failed. Do you know why?

**Review by alexmt — APPROVED** [review]
Thank you for unblocking me! LGTM

**Review by alexmt — CHANGES_REQUESTED** [review]
Just noticed CI failed. @huikang , Can you please run `go mod download && go mod tidy` to make codegen happy?

**Review by alexmt — APPROVED** [review]

**Comment by huikang** [comment]
@jessesuen , @alexmt 's suggestion makes the codegen test passed. Thanks.

**Pull request merged**
